---
output: 
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    toc: no
    number_sections: no
    latex_engine: xelatex
    pandoc_args: --lua-filter=../../../multibib.lua

title: |
  | An Incomplete Recipe: 
  | One-Dimensional Latent Variables Do Not Capture
  | the Full Flavor of Democratic Support

subtitle: |
  Memo to Reviewer and Editor

date: " "
editor_options: 
  markdown: 
    wrap: sentence
tables: true # enable longtable and booktabs
citation_package: natbib
citeproc: false
fontsize: 12pt
indent: true
linestretch: 1.5 # double spacing using linestretch 1.5
bibliography:
  text: ../../../dcpo-demsupport-data.bib
biblio-style: apsr
citecolor: black
linkcolor: black
endnote: no
---

We thank Reviewer 1 for carefully reading our revision and highlighting the narrative issues.
In particular, R1 suggested that "the setup needs to be cleaner," noting that our prior resubmission dove "too deep into the weeds of two papers" without explanation and introduced various terms without defining them, and the Associate Editor agreed that we could improve the presentation.

We revised the introduction at pages 1-3 to address this suggestion, while remaining mindful of R1's previous exhortation "to make clear what the take-away message should be."
Specifically, we took pains to connect the subsequent paragraphs to the point made in the opening paragraph, that a large literature reveals that "claims to favor democracy in the abstract do not consistently represent either commitments to _liberal_ democracy or opposition to actions that undermine it" (page 1).
The second paragraph explains that the new one-dimensional latent-variable measures used in a series of prominent works---we note here that the seven works referred to in this paragraph, each less than 5 years old, have already been cited a total of over 600 times---ignore this finding and instead compile survey questions tapping only support for democracy in the abstract.
The third paragraph explicitly ties these two points together: "we contend that compiling many questions about democracy in the abstract into a single one-dimensional latent variable should not be expected to change the fact that such questions do not accurately assess" the complexity of attitudes toward democracy.
The fourth then previews our finding that validation tests of "the sort of one-dimensional measure used in the recent line of latent-variable-driven research" against questions "that map the dimensions of support for liberal democracy and opposition to its erosion" reveal little relationship between the two.
The introduction's last paragraph then states our two take-away messages: that generally researchers using latent variables need to be sure to validate them before use and specifically the works based on the latent variable of democratic support should not be considered credible.

Throughout the introduction, we avoid raising peripheral points (e.g., the multidimensionality of democracy itself offered in the original submission and the weedy details of the Claassen 2020a and Hu, Tai, and Solt 2022 papers in the first revision) and so maintain the clarity of our argument.
We provide succinct answers to R1's questions about the latent-variable method used in this line of recent works and about the Churchill question in the next section, at page 3.


Thank you once again for the opportunity to improve our paper. 
We believe it is now stronger as a result of your valuable feedback and hope that you agree.


